[Service]
Type=oneshot
RemainAfterExit=yes

ExecStart=
ExecStart=-udevadm --debug trigger --type=all --action=add --prioritized-subsystem=module,block,tpmrm,net,tty,input

# Log to console.
StandardOutput=tty
StandardError=inherit
